---
title: "Cell Barcodes"
author: "Jake Sauter"
date: "3/8/2021"
output: 
  html_document: 
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment=NA)
```

```{r}
library(magrittr)

{
  base_dir <- 'data/'
  
  ctrl_1_unfiltered_count_file <-  paste0(base_dir, 'ctrl_1_unfiltered_count_barcodes.tsv')
  ctrl_2_unfiltered_count_file <-  paste0(base_dir, 'ctrl_2_unfiltered_count_barcodes.tsv')
  ctrl_3_unfiltered_count_file <-  paste0(base_dir, 'ctrl_3_unfiltered_count_barcodes.tsv')
  myd88_1_unfiltered_count_file <- paste0(base_dir, 'myd88_1_unfiltered_count_barcodes.tsv')
  myd88_2_unfiltered_count_file <- paste0(base_dir, 'myd88_2_unfiltered_count_barcodes.tsv')
  myd88_3_unfiltered_count_file <- paste0(base_dir, 'myd88_3_unfiltered_count_barcodes.tsv')
  
  ctrl_1_count_file <-  paste0(base_dir, 'ctrl_1_count_barcodes.tsv')
  ctrl_2_count_file <-  paste0(base_dir, 'ctrl_2_count_barcodes.tsv')
  ctrl_3_count_file <-  paste0(base_dir, 'ctrl_3_count_barcodes.tsv')
  myd88_1_count_file <- paste0(base_dir, 'myd88_1_count_barcodes.tsv')
  myd88_2_count_file <- paste0(base_dir, 'myd88_2_count_barcodes.tsv')
  myd88_3_count_file <- paste0(base_dir, 'myd88_3_count_barcodes.tsv')
  
  ctrl_1_vdj_file <-  paste0(base_dir, 'ctrl_1_vdj_barcodes.json')
  ctrl_2_vdj_file <-  paste0(base_dir, 'ctrl_2_vdj_barcodes.json')
  ctrl_3_vdj_file <-  paste0(base_dir, 'ctrl_3_vdj_barcodes.json')
  myd88_1_vdj_file <- paste0(base_dir, 'myd88_1_vdj_barcodes.json')
  myd88_2_vdj_file <- paste0(base_dir, 'myd88_2_vdj_barcodes.json')
  myd88_3_vdj_file <- paste0(base_dir, 'myd88_3_vdj_barcodes.json')
  
  ctrl_1_multi_vdj_file <-  paste0(base_dir, 'ctrl_1_multi_vdj_cell_barcodes.json')
  ctrl_2_multi_vdj_file <-  paste0(base_dir, 'ctrl_2_multi_vdj_cell_barcodes.json')
  ctrl_3_multi_vdj_file <-  paste0(base_dir, 'ctrl_3_multi_vdj_cell_barcodes.json')
  myd88_1_multi_vdj_file <- paste0(base_dir, 'myd88_1_multi_vdj_cell_barcodes.json')
  myd88_2_multi_vdj_file <- paste0(base_dir, 'myd88_2_multi_vdj_cell_barcodes.json')
  myd88_3_multi_vdj_file <- paste0(base_dir, 'myd88_3_multi_vdj_cell_barcodes.json')
  
  ctrl_1_multi_count_file <-  paste0(base_dir, 'ctrl_1_multi_count_barcodes.tsv')
  ctrl_2_multi_count_file <-  paste0(base_dir, 'ctrl_2_multi_count_barcodes.tsv')
  ctrl_3_multi_count_file <-  paste0(base_dir, 'ctrl_3_multi_count_barcodes.tsv')
  myd88_1_multi_count_file <- paste0(base_dir, 'myd88_1_multi_count_barcodes.tsv')
  myd88_2_multi_count_file <- paste0(base_dir, 'myd88_2_multi_count_barcodes.tsv')
  myd88_3_multi_count_file <- paste0(base_dir, 'myd88_3_multi_count_barcodes.tsv')
}
```


```{r}
ctrl_1_full_barcodes <- read.csv(ctrl_1_unfiltered_count_file) %>% unlist()
ctrl_1_cell_barcodes <- read.csv(ctrl_1_count_file) %>% unlist()
ctrl_1_vdj_barcodes <- rjson::fromJSON(file=ctrl_1_vdj_file) %>% unlist()
ctrl_1_multi_vdj_barcodes <- rjson::fromJSON(file=ctrl_1_multi_vdj_file) %>% unlist()
ctrl_1_multi_cell_barcodes <- read.csv(ctrl_1_multi_count_file) %>% unlist()
```

```{r}
cat('Number of unfiltered barcodes: ', length(ctrl_1_full_barcodes), '\n')
cat('Number of cell-associated barcodes: ', length(ctrl_1_cell_barcodes))
```

```{r}
if (length(setdiff(ctrl_1_cell_barcodes, ctrl_1_full_barcodes)) == 0) {
  cat('All cell-associated barcodes found within unfiltered barcodes\n')
}

cat('Number of vdj called cells: ', length(ctrl_1_vdj_barcodes), '\n')
cat('Number of vdj called cells (with multi): ', length(ctrl_1_multi_vdj_barcodes))
```

```{r}
cat('Number of vdj called cells from cellranger vdj, filtered by cellranger count called cells: ', length(intersect(ctrl_1_cell_barcodes, ctrl_1_vdj_barcodes)))
```


